for path <- :code.get_path(),
    Regex.match?(~r/phx_new-[\w\.\-]+\/ebin$/, List.to_string(path)) do
  Code.delete_path(path)
end

defmodule Exp.New.MixProject do
  use Mix.Project

  @version "0.0.1"

  # If the elixir requirement is updated, we need to update:
  #
  #   1. all mix.exs generated by the installer
  #   2. guides/introduction/installation.md
  #   3. guides/deployment/releases.md
  #   4. test/test_helper.exs at the root
  #   5. installer/lib/mix/tasks/phx.new.ex
  #
  @elixir_requirement "~> 1.14"

  def project do
    [
      app: :phx_new,
      start_permanent: Mix.env() == :prod,
      version: @version,
      elixir: @elixir_requirement,
      deps: deps(),
      package: [],
      preferred_cli_env: [docs: :docs],
      description: """
      Express Deploy and Phoenix framework project generator.

      Provides a `mix exp.new` task to bootstrap a new Elixir application
      with Express Deploy and Phoenix dependencies.
      """
    ]
  end

  def application do
    [
      extra_applications: [:eex, :crypto]
    ]
  end

  def deps do
    [
      {:ex_doc, "~> 0.24", only: :docs}
    ]
  end
end
